### PR TITLE
Bzimmerman c make

### PR DESCRIPTION
**Pull request by bzimmerman-qb**

### CODE REVIEW

**Comment by sappo** [comment]
Hi @bzimmerman-qb,

Thanks for your contribution. But 24 commits in one pull request is really messy, thus I can't really figure out what problem you did solve. 

Could you please read our contribution guideline https://github.com/zeromq/czmq/blob/master/CONTRIBUTING.md and open another pull request!

**Comment by hintjens** [comment]
Hmm, like @sappo says, this is not a valid patch by our standards.

24 commits, four files changed, and the actual changes don't seem to match the commits fully. I guess there is some git confusion here.

My advice is to take a fresh fork of CZMQ, then re-apply your changes (they are quite small) by hand, using the proper "Problem: / Solution:" style for each commit.

That is, each commit message has as title, "Problem: what is broken/undoable here" and a body that explains the solution. One commit = one problem. That lets us rapidly catch obvious mistakes.

Thanks

**Comment by bzimmerman-qb** [comment]
Peter,

  This was an error submission along with the one to zmq.  It was supposed to go to the forks created by qbase.  I realize these are autogenerated and will be rewritten.

  Apologize for inconvenience.

Thanks,
Bryan Z

**Comment by hintjens** [comment]
No problem. In general maintaining forks over time is a bad idea. You
should push your patches one by one back to CZMQ, using the
problem/solution style I explained.

**Pull request closed without merging**
