### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by sappo**

### CODE REVIEW

**Comment by jemc** [comment]
The build is broken, but it's not this PR's fault :wink:.

**Comment by sappo** [comment]
Hmm...weird, why isn't that error showing on my machine?

**Comment by jemc** [comment]
You probably need the compiler flag `-Werror=format-security`.

**Comment by sappo** [comment]
Okay, is this a default in the travis containers.

**Comment by jemc** [comment]
As far as I know, it is a default in Ubuntu.

**Comment by sappo** [comment]
What do you think about explicitly settings this flag?

**Pull request merged**
