### PR TITLE
Problem: zframe_strhex is needlessly using zmalloc

### PR DESCRIPTION
**Pull request by Asmod4n**
Solution: change it to malloc.

### CODE REVIEW

**Comment by Asmod4n** [comment]
Error is unrelated.

**Comment by sappo** [comment]
@Asmod4n What's the difference anyhow? Is there a performance loss?

**Comment by Asmod4n** [comment]
@sappo zmalloc nullifies the buffer, which has a performance hit. But since zframe_strhex doesn't read the buffer there is no need to do that.

**Comment by sappo** [comment]
@Asmod4n thanks :+1:

**Pull request merged**
