### PR TITLE
added cast to correct error: "TCHAR *" is incompatible with parameter of type "const char *"

### PR DESCRIPTION
**Pull request by sgluss**
see issue and discussion of fix here:
https://github.com/zeromq/czmq/issues/1785

### CODE REVIEW

**Comment by bluca** [comment]
@evoskuil what else could be done to fix the problem? Are you familiar with the Windows API being used there?

**Comment by evoskuil** [comment]
I am very familiar but unfortunately traveling with only my phone, so hard to do much. Ultimately UTF8 Everywhere is the proper solution. Few projects have done this, but we have done so in Libbitcoin. See other thread for quick fix recommendations.

**Comment by bluca** [comment]
@evoskuil ok thanks. Given there's a build breakage and it's a new draft API so not very used, I propose to merge this as a quick bandaid to get the whole library working again in Windows, and then a proper fix can be researched without rush.

**Comment by sgluss** [comment]
In the meantime I'll keep investigating why VS2017 is having trouble with the TCHAR. This code compiled without complaint in Ubuntu 16.04

**Comment by evoskuil** [comment]
[Issue 994](https://github.com/zeromq/czmq/issues/994) explains the core issue in more detail.

**Comment by evoskuil** [comment]
This is a local fix: https://github.com/zeromq/czmq/pull/1793

**Pull request merged**
