### PR TITLE
Problem: need to test new cffi bindings

### PR DESCRIPTION
**Pull request by vyskocilm**
Solution: regenerate using latest zproject

### CODE REVIEW

**Comment by sappo** [comment]
I do have the setuptools covered ;)

**Comment by vyskocilm** [comment]
@sappo  great! I'll stop to think about it then ;-)

**Comment by sappo** [comment]
@vyskocilm your changes are more substantial than I thought and it was simply to hot in my appartement this weekend to get any work done. Do you need the changes i.e. setup.py soon?

What I've done is:
* setup.py
* Generation of thin wrapper classes (incomplete, works for numbers and strings though)
* Generation of a wrapper library to properly invoke the CLASS destroy method from cffi

**Comment by vyskocilm** [comment]
Hi Kevin,

No worries. I spent a weekend outside, so had no time either. It would be
great to have setup.py, I can do it myself, but have no big experience here.

For class generator ...are you talking about having more pythonic class?
That would be awesome. Just submit whatever you have and I will help you

Dne 29. 5. 2017 7:47 napsal uživatel "Kevin Sapper" <
notifications@github.com>:

**Pull request merged**
