### PR TITLE
Problem: zproc_run method can't be expressed as zproject API model

### PR DESCRIPTION
**Pull request by vyskocilm**
Solution: see pull requests

In fact code is way more straightforward than before, because argv/env are built right before execve and not passed from zproc_run to actor and pipe handler.

### CODE REVIEW

**Comment by bluca** [comment]
Nice! But:

```
src/zproc.c: In function 'zproc_test':
src/zproc.c:986:17: error: unused variable 'xenvp' [-Werror=unused-variable]
src/zproc.c:985:17: error: unused variable 'xargv' [-Werror=unused-variable]
src/zproc.c: At top level:
src/zproc.c:173:1: error: 'arr_size' defined but not used [-Werror=unused-function]
```

want to have a look before or after merging?

**Comment by vyskocilm** [comment]
How it's possible make run well locally? I will fix it

Dne 24. 3. 2017 2:26 PM napsal uživatel "Luca Boccassi" <
notifications@github.com>:

**Comment by bluca** [comment]
Different compiler version/setting? Those are 2 warnings treated as errors

**Comment by bluca** [comment]
Thanks!

**Pull request merged**
