### PR TITLE
Problems: zgossip too chatty, binds to hard-coded TCP port, out of date with zproto

### PR DESCRIPTION
**Pull request by bluca**
Solutions: see commits

### CODE REVIEW

**Comment by wesyoung** [comment]
funny, i was just running across some of that in zyre too. forgot about the if/verbose stuff.

**Comment by jimklimov** [comment]
Just in case, why change back from `freen` to `free`? 

And what's about `...get()` vs `...resolv()`?

**Comment by bluca** [comment]
> Just in case, why change back from freen to free?

That's a manual change that is not in zproto so it gets overwritten - it's not very useful in these cases so it's not worth keeping it manually in place

> And what's about ...get() vs ...resolv()?

zconfig_resolve doesn't exist:

https://github.com/zeromq/czmq/blob/master/api/zconfig.api

**Comment by bluca** [comment]
> zconfig_resolve doesn't exist:
>
> https://github.com/zeromq/czmq/blob/master/api/zconfig.api

Was renamed by https://github.com/zeromq/czmq/pull/988

**Pull request merged**
