### PR TITLE
Working on JNI Android builds

### PR DESCRIPTION
**Pull request by hintjens**

### CODE REVIEW

**Comment by jemc** [comment]
@hintjens - If you've found the `qt-android` build to be useful outside the context of Qt, then you can feel free to rename it to something more appropriate.  I've always suspected that it would be compatible with other JNI efforts, but never fully confirmed it.

**Comment by hintjens** [comment]
I think we can kill the old android build and rename qt-android...

**Comment by jemc** [comment]
:+1:, since no one seems to be maintaining the other one anyway

**Comment by hintjens** [comment]
Right, will do that then.

**Pull request merged**
