### PR TITLE
CLASS declarations for zdir, zfile, zdir_patch.

### PR DESCRIPTION
**Pull request by twhittock**

### CODE REVIEW

**Comment by sappo** [comment]
A zdir test failed, can you check please.
```
Assertion failed: dummy == 1 (src/signaler.cpp:280)
/bin/bash: line 5: 4674 Aborted ${dir}$tst
```
There's more information in the travis build.

**Comment by twhittock** [comment]
Huh? I don't see that text in the travis site? All builds passed "* zdir: OK" but 2 hung for 10 mins due to Travis env...

**Comment by sappo** [comment]
@twhittock you're right, its gone somehow *head scratching

**Comment by jemc** [comment]
@sappo @twhittock 
The failure looked unrelated, so I restarted the travis build.  I meant to check back and merge if it was okay, but got distracted with other things.

**Pull request merged**
