### PR TITLE
Problem: Homebrew must run under Ruby 2.3

### PR DESCRIPTION
**Pull request by AntonBarwald**
Solution: Run 'brew update' before 'brew install package_name'

### CODE REVIEW

**Comment by AntonBarwald** [comment]
Maybe there is a drawback to do 'brew update' each time?

**Comment by bluca** [comment]
This should be solved when a new osx image is deployed on Wednesday, that's why I've left it alone. A brew update unfortunately takes minutes, making the already slow osx builds even slower :-(

**Comment by AntonBarwald** [comment]
@bluca Yes, I saw that it was making it slower 👎. Should I close this one since it will be fixed with new OS X image on Wednesday?

**Comment by bluca** [comment]
Yes please, if you don't mind. We can then reopen if the deployment doesn't solve it: https://blog.travis-ci.com/2017-10-16-a-new-default-os-x-image-is-coming

**Comment by bluca** [comment]
Looks like they haven't fixed it yet. Slightly different fix to run brew update only in builds that actually need brew https://github.com/zeromq/czmq/pull/1794

**Pull request closed without merging**
