### PR TITLE
problem: ztimerset failing on stable libzmq release

### PR DESCRIPTION
**Pull request by somdoron**
only run test when building with libzmq from version 4.2

### CODE REVIEW

**Comment by bluca** [comment]
:+1:

**Comment by somdoron** [comment]
@bluca  anyway to avoid compile this class completly if not using libzmq > 4.2?

**Comment by bluca** [comment]
Mmh I don't think we have that facility in the build system at the moment. Would be useful indeed. But I guess the problem would be that the public header (and thus API+ABI) would change in a stable build depending on the underlying version of libzmq.

**Comment by somdoron** [comment]
ok thanks

**Pull request merged**
