### PR TITLE
Fix/zproxy assertion fail

### PR DESCRIPTION
**Pull request by piskorzj**
This pull request fixes concurrency (or hazard) issues I've observed when working with XPUB/XSUB proxy on distributed system.

Related issue #1445.

### CODE REVIEW

**Comment by bluca** [comment]
@piskorzj - it seems the tests are broken:

on older releases:
lt-czmq_selftest: src/zproxy.c:547: zproxy_test: Assertion `sink' failed.

on 4.1:
 zproxy: E: 16-05-18 19:04:49 zproxy: invalid endpoints 'inproc://backend'

**Comment by piskorzj** [comment]
I found out why. ZeroMQ before 4.0 forbids connecting before bind in *inproc* transport. On osx 4.1 I have no idea why, can't reproduce because I don't have Mac.

Change from inproc to ipc solves older releases issue.

**Comment by sappo** [comment]
@piskorzj you'll have to open another PR

**Comment by sappo** [comment]
@piskorzj one more note. For further contributions could you please read our CONTRIBUTION.md. Thanks!

**Comment by piskorzj** [comment]
@sappo Ok, I get what I did wrong. I used to use commits as single logic change in code, and branch as solution to problem, while you expect commit to be solution of a single problem. I'll do better next time.
Thanks!

**Pull request merged**
