### PR TITLE
Include zsock_option functions into zsock.xml

### PR DESCRIPTION
**Pull request by paddor**
This also fixes paths to the license file and actually turns on the `<include>` tag within class API XML files.

This is related to #1164.

### CODE REVIEW

**Comment by sappo** [comment]
@paddor that's great stuff. Thanks.

I would encourage you though, to use the zeromq style commits in the further:
```
Problem: <describe the minmal problem you're having>
Solution: <explain how you solved your problem>
```
If you need an example check the git log there are lots of them ;)

**Comment by paddor** [comment]
@sappo You're welcome. :sunglasses: 

Sure, I'll use zeromq style commits from now on.

And thanks for adding me to the teams! Does that mean I don't need to create pull requests anymore? :blush:

**Comment by sappo** [comment]
@paddor you should read our code contract http://rfc.zeromq.org/spec:22

There are two basic rules though, we NEVER commit directly to upstream master. And we NEVER merge our own pull request.

**Comment by paddor** [comment]
@sappo That makes a lot of sense. Thanks again.

**Comment by sappo** [comment]
You are welcome!
Am 20.11.2015 5:25 nachm. schrieb "Patrik Wenger" <notifications@github.com

**Comment by hintjens** [comment]
@paddor the zsock* scripts are kind of confusing now.

I'd like to clean these up. At the least, these things bother me:

* we seem to be generating both XML and C/H for the V3 socket options API.
* we are using 'zsock_option' for the old generated code
* we are using 'zsock_options' for the new generated code (via api/)
* we have code generators in the api directory (they should all be in the same place)

Do you intend to clean this up still or shall I do it?

**Pull request merged**
