### PR TITLE
Problem: can't build czmq on osx

### LINKED ISSUE #1834: environ not declared on osx
I just noticed a bug compiling on OSX High Sierra. 
src/zproc.c:537:19: error: use of undeclared identifier 'environ'
            env = environ;

To be able to successfully compile you need to comment the else clause at line 537 of src/zproc.c then all is good. OSX does not provide environ support it seems.

### PR DESCRIPTION
**Pull request by vyskocilm**
Solution: use _NSGetEnviron () routine to get environ variable on OSX

I've no access to OSX, someone should check if it builds and works before merging. Should fix #1834

### CODE REVIEW

**Comment by bluca** [comment]
Travis doesn't seem to be happy:

```
src/zproc.c:542:17: error: incompatible pointer types assigning to 'char **' from 'char ***'; dereference with * [-Werror,-Wincompatible-pointer-types]
            env = _NSGetEnviron ();
```

**Comment by bluca** [comment]
This time Linux complains:

```
/home/travis/build/zeromq/czmq/src/zproc.c: In function 's_zproc_execve':
/home/travis/build/zeromq/czmq/src/zproc.c:544:19: error: 'environ' undeclared (first use in this function)
             env = environ;
```

**Comment by vyskocilm** [comment]
@bluca weird, I'd expect environ to be available. I added declaration for unix if _GNU_SOURCE is not defined. Hope it will helps

**Comment by vyskocilm** [comment]
An another attempt - I streamlined the code and OSX now use _NSGetEnviron (), other unixes have explicit declaration of `extern char **environ`.

**Comment by bluca** [comment]
OSX CI is completely clogged

**Comment by bluca** [comment]
Still doesn't seem to work:

```
src/zproc.c:63:18: error: initializer element is not a compile-time constant
char **environ = *_NSGetEnviron (); // issue#1836
```

**Pull request merged**
