### PR TITLE
Problem: New zcertstore APIs were not marked as "draft".

### PR DESCRIPTION
**Pull request by petehayes102**
Solution: Mark as "draft".

As discussed in #1413.

### CODE REVIEW

**Comment by bluca** [comment]
Thanks!

Unfortunately it looks like the draft system causes problems with typedefs. It's not an issue with your changes, but in zproject I think. I'll have a look.

**Comment by petehayes102** [comment]
Damn... Sorry for the bother. Let me know if I can help.

**Comment by bluca** [comment]
No problem, not your fault! This actually helped uncover an issue in zproject :-)
I've got a solution, I'll send a PR shortly.

**Comment by bluca** [comment]
Opened https://github.com/zeromq/zproject/pull/600 to fix in zproject, will regenerate here once merged.

Ah also, for future contributions, could you please have a separate commit with the result of the zproject regen? This allows to cleanly separate in the git history the api/* changes from the zproject regeneration.

**Comment by petehayes102** [comment]
@bluca Yep, will do. One of these days I'll get a handle on the conventions! :)

**Pull request merged**
