### PR TITLE
Problem: uuid library not used

### PR DESCRIPTION
**Pull request by bkmit**
Solution: list uuid in project.xml as optional default on if found and regenerate project

### CODE REVIEW

**Comment by bluca** [comment]
Hi, I think your local version of zproject is out of date, could you please make sure it has the latest changes? Otherwise this is breaking a few things that were fixed recently. THanks!

**Comment by bkmit** [comment]
You are right @bluca ! Good catch, thank you.

**Comment by bluca** [comment]
Thanks!

For the next contributions, please add the regeneration from zproject in a separate git commit. This helps keep configuration changes more visible, since the regeneration is very noisy usually.

**Comment by bkmit** [comment]
Got it. Will do commit regeneration alone.

**Pull request merged**
