### PR TITLE
Problem: Wikidot docs are not automatically updated

### PR DESCRIPTION
**Pull request by sappo**
Solution: Add a new build script that will upload the master
revision of the docs to Wikidot on every Non-PR build.

### CODE REVIEW

**Comment by bluca** [comment]
great stuff, thanks!

**Comment by sappo** [comment]
It does not work for deployments though! Why? Because PERL :(

**Comment by bluca** [comment]
lol!
what's the issue?

**Comment by sappo** [comment]
The versions for which the guide is generated is manually set in bash and perl.

**Pull request merged**
