### PR TITLE
Update ruby binding for referring LIBCZMQ_PATH

### PR DESCRIPTION
**Pull request by mrkn**
I made ruby binding can be refer LIBCZMQ_PATH for looking up libczmq in https://github.com/zeromq/zproject/pull/697 and https://github.com/zeromq/zproject/pull/698 .
To available this feature I want update ruby binding.

### CODE REVIEW

**Comment by paddor** [comment]
@bluca This pull request affects a file that is 100% generated from the API using zguide.

**Comment by paddor** [comment]
@mrkn We have to work out a more generic solution for this. Maybe you didn't realize it, but you changed a file that's 100% generated using zproject and CZMQ's API definitions. The next time someone regenerates the (Ruby) bindings in this project, your change will be gone.

I'll open a zproject issue to tackle this issue in a more generic way. Please read there for more details.

**Comment by mrkn** [comment]
@paddor I made this change using zproject after my pull-requests to zproject https://github.com/zeromq/zproject/pull/697 and https://github.com/zeromq/zproject/pull/698 are merged.
Is this incorrect?

**Comment by paddor** [comment]
Sorry, my bad! I didn't see your change in zproject. 😅 Looks good!

**Comment by mrkn** [comment]
@paddor No problem.  Thanks for checking my changes :)

**Pull request merged**
