### PR TITLE
Problem: microhttpd version is to high and is not available and most distros

### PR DESCRIPTION
**Pull request by somdoron**
Solution: have a version condition around the method causing the issue and downgrade the version

### CODE REVIEW

**Comment by somdoron** [comment]
@bluca it seems the CI is not going to pass, not sure why yet.
I won't have time until the flight, you can make it if you have time, if not I will do it tomorrow

**Comment by somdoron** [comment]
I think I fixed the CI

**Comment by somdoron** [comment]
I must be doing something that is not compatible with the version...
I will with a VM tomorrow

**Comment by bluca** [comment]
ok, thanks

**Comment by sappo** [comment]
Is it ready for merging?

**Comment by somdoron** [comment]
Yes

**Comment by bluca** [comment]
JNI looks unhappy, but can be fixed later if you prefer:

```
/home/travis/build/zeromq/czmq/bindings/jni/src/main/c/org_zeromq_czmq_ZhttpRequest.c:140:14: error: redefinition of 'match_' with a different type: 'jboolean' (aka 'unsigned char') vs 'char *'
    jboolean match_ = (jboolean) zhttp_request_match ((zhttp_request_t *) (intptr_t) self, method_, match_);
             ^
/home/travis/build/zeromq/czmq/bindings/jni/src/main/c/org_zeromq_czmq_ZhttpRequest.c:139:11: note: previous definition is here
    char *match_ = (char *) (*env)->GetStringUTFChars (env, match, NULL);
```

**Comment by somdoron** [comment]
Yes, I will take a look later

**Pull request merged**
