### PR TITLE
set zactor threadname for convenience

### PR DESCRIPTION
**Pull request by sphaero**
Problem: sometimes it's hard to find what thread is a zactor
Solution: set the thread name

It would be nicer to be able to set a thread name by the user but we do not have access to the thread struct.Couldn't find the methods for windows so on windows no thread name is set. Other approach could also be to set some thread local var which is easy to find in a debugger.

### CODE REVIEW

**Comment by sphaero** [comment]
I'm rerunning the failed jobs as zproject wasn't updated yet. MacOS builds are hanging as well with no output. I managed to get some logs by cancelling the job:

```
/Applications/Xcode_14.2.app/Contents/Developer/usr/bin/make  check-TESTS check-local
============================================================================
Testsuite summary for czmq 4.2.2
============================================================================
# TOTAL: 0
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
rm -rf "src/selftest-rw"
mkdir -p "src/selftest-rw"
   COPYDIR  src/selftest-ro
make[3]: Circular src/selftest-ro <- src/selftest-ro dependency dropped.
/bin/sh ./libtool --mode=execute ./src/czmq_selftest
Error: The operation was canceled.
```
It's hanging at the selftest :confused:

**Comment by sphaero** [comment]
Seems czmq is missing the builds/ios dirs. 

```
+ git --version
git version 2.39.1
++ git --no-pager diff -w
+ [[ -n '' ]]
++ git status -s
+ [[ -n ?? builds/ios/ ]]
+ git status -s
?? builds/ios/
zproject generated new files!
+ echo 'zproject generated new files!'
+ exit 1
```

**Comment by sphaero** [comment]
I guess we requested that by doing `<target name = "*" />`

I've added the files as well

**Comment by sphaero** [comment]
Anybody experience with OBS? It's failing somehow at:
```
[   41s] Unpacking czmq-3.0.0+git20230126.obscpio ...
[   41s] 16085 blocks
[   41s] Running build time source services...
[   41s] Traceback (most recent call last):
[   41s]   File "/usr/lib/obs/service/tar", line 30, in <module>
[   41s]     main()
[   41s]   File "/usr/lib/obs/service/tar", line 26, in main
[   41s]     TarSCM.run()
[   41s]   File "/usr/lib/obs/service/TarSCM/__init__.py", line 39, in run
[   41s]     task_list.process_list()
[   41s]   File "/usr/lib/obs/service/TarSCM/tasks.py", line 118, in process_list
[   41s]     self.process_single_task(task)
[   41s]   File "/usr/lib/obs/service/TarSCM/tasks.py", line 173, in process_single_task
[   41s]     self.args = self.check_for_branch_request(args)
[   41s]   File "/usr/lib/obs/service/TarSCM/tasks.py", line 156, in check_for_branch_request
[   41s]     if j['object_kind'] == 'merge_request':
[   41s] KeyError: 'object_kind'
[   41s] service run failed for service 'tar'
```

Might be related? https://github.com/openSUSE/obs-service-tar_scm/issues/446

**Comment by bluca** [comment]
> Anybody experience with OBS? It's failing somehow at:
> 
> ```
> [   41s] Unpacking czmq-3.0.0+git20230126.obscpio ...
> [   41s] 16085 blocks
> [   41s] Running build time source services...
> [   41s] Traceback (most recent call last):
> [   41s]   File "/usr/lib/obs/service/tar", line 30, in <module>
> [   41s]     main()
> [   41s]   File "/usr/lib/obs/service/tar", line 26, in main
> [   41s]     TarSCM.run()
> [   41s]   File "/usr/lib/obs/service/TarSCM/__init__.py", line 39, in run
> [   41s]     task_list.process_list()
> [   41s]   File "/usr/lib/obs/service/TarSCM/tasks.py", line 118, in process_list
> [   41s]     self.process_single_task(task)
> [   41s]   File "/usr/lib/obs/service/TarSCM/tasks.py", line 173, in process_single_task
> [   41s]     self.args = self.check_for_branch_request(args)
> [   41s]   File "/usr/lib/obs/service/TarSCM/tasks.py", line 156, in check_for_branch_request
> [   41s]     if j['object_kind'] == 'merge_request':
> [   41s] KeyError: 'object_kind'
> [   41s] service run failed for service 'tar'
> ```
> 
> Might be related? [openSUSE/obs-service-tar_scm#446](https://github.com/openSUSE/obs-service-tar_scm/issues/446)

yes it's a known issue, ignore those

**Pull request merged**
