### PR TITLE
Problem: missed argument on zframe_set_group model

### PR DESCRIPTION
**Pull request by taotetek**
I missed the argument in the model for zframe_set_group - fixed!

### CODE REVIEW

**Comment by somdoron** [comment]
@taotetek, the method already exposed in the api, new they defined twice...

**Comment by somdoron** [comment]
As draft

**Comment by taotetek** [comment]
@somdoron aha! I haven't done a PR since the new draft stuff was added. Doh!

**Comment by taotetek** [comment]
@somdoron I'll close this one and fix, thanks for the info! I ended up thinking it wasn't exported when trying to link rsyslog against it - I must not be passing the right flags to build w/ draft.

**Pull request closed without merging**
