### PR TITLE
Problem: czmq is out of date with latest changes to zproject

### PR DESCRIPTION
**Pull request by sappo**
Solution: Regenerate bindings and selftests with zproject

### CODE REVIEW

**Comment by madebr** [comment]
Sorry about the inconvenience. Will these patches solve the divergence introduced by me?

**Comment by hintjens** [comment]
Oh,  no apologies!, This is how we work,  gradual improvement. Your patches
are welcome.

**Comment by sappo** [comment]
@madebr no worries. It's great that you took the time and effort to apply your changes to zproject.

**Comment by sappo** [comment]
Something is still wrong with cmake though. @madebr I think we need to apply the changes you made to cmake to zproject as well. Sadly I don't have enough knowledge about cmake to do the fix myself.

**Comment by sappo** [comment]
obsolete pull request due to #1135

**Pull request closed without merging**
