### PR TITLE
Working on Node.js binding

### PR DESCRIPTION
**Pull request by hintjens**

### CODE REVIEW

**Comment by bluca** [comment]
@hintjens - the diff shows that some broken Debian packaging stuff that I removed a while back are being added back. Could you please double check? It's files that are no longer generated and were removed from git:

packaging/debian/CZMQ-dev.install
packaging/debian/CZMQ.install
packaging/debian/czmq.dsc

**Comment by hintjens** [comment]
Oh, sorry, will fix as soon as I get back online... Please don't merge yet
then.

**Comment by bluca** [comment]
Thanks!

**Comment by hintjens** [comment]
@bluca should be good now. Sorry about that...

**Comment by bluca** [comment]
Great, thanks for fixing it!

**Pull request merged**
