### PR TITLE
Problem: zsubproc broke Windows builds of czmq

### PR DESCRIPTION
**Pull request by vyskocilm**
Solution: use ifdefs more aggresivelly and convert more functions to be stubs only on Windows.

### CODE REVIEW

**Comment by vyskocilm** [comment]
Fixes issues from https://github.com/zeromq/czmq/pull/1636

**Comment by bluca** [comment]
Still a bit unhappy:

```
C:\projects\czmq\src\zsp.c(61): error C2065: 'use_stdin': undeclared identifier 
```

Do you want me to wait to merge until it builds?

**Comment by vyskocilm** [comment]
I'd say lets make Windows build working before the merge. It's challenging a bit for me as there are no Windows around me, however zsp should be done too.

**Comment by bluca** [comment]
Yeah it's painful, I have the same problem all the time.

Note that Appveyor allows you to simply login with Github and ran the tests on any push, just like Travis, in case that can be useful

**Comment by vyskocilm** [comment]
Thanks, I've added proper skip for unit test and it should pass now. Thanks for the advice on running CI on push.

**Comment by bluca** [comment]
Great, thanks!

**Comment by bluca** [comment]
@vyskocilm there's still some trouble on OSX and Linux, could you please have a look?

https://travis-ci.org/zeromq/czmq/builds/210602364

**Comment by vyskocilm** [comment]
Sure, I'll try to fix it. Btw how about a new name? Zproc zpipe?

Dne 13. 3. 2017 11:46 PM napsal uživatel "Luca Boccassi" <
notifications@github.com>:

**Comment by bluca** [comment]
what about merging the new API with the existing zproc class (which is still draft)?

**Pull request merged**
