### PR TITLE
Problem: zproc readability and usability issues

### PR DESCRIPTION
**Pull request by vyskocilm**
Solution: put macro magic to czmq_prelude.h, so other users will benefit from it. Simplify the zproc.c code a bit.

### CODE REVIEW

**Comment by jimklimov** [comment]
Good idea. Would you care to also change the 2 or so other usecases? Or are they not as simple (iirc one had different logics too)?

**Comment by jimklimov** [comment]
Good idea. Would you care to also change the 2 or so other usecases? Or are they not as simple (iirc one had different logics too)?

**Comment by vyskocilm** [comment]
@bluca  and otherts - sorry for pushing more patches there, I thought the first PR is already merged :-D

**Comment by jimklimov** [comment]
Quite LGTM! Thanks for cleaning this up! ;)

**Pull request merged**
