### PR TITLE
Introduce zsys.api

### PR DESCRIPTION
**Pull request by diorcety**
Use api file in order to support zsys in different bindings. cf #1684
The only api change is zsys_file_size return type.
 zsys_file_size return type is ssize_t
stat_buf.st_size type is off_t
so i replaced zsys_file_size return type by off_t which is file_size type in the api file

### CODE REVIEW

**Comment by bluca** [comment]
Sorry, but we cannot make backward incompatible changes to the public API.

Is there any way to keep zsys_file_size the same?

**Comment by bluca** [comment]
Keeping its definition outside of the API file (leave it in the header along with the zsys_interrupted definitions) would be fine IMHO, given it's never been available in the bindings anyway

**Comment by jemc** [comment]
@diorcety Great work!

To avoid changing the signature of `zsys_file_size` as @bluca has asked, zproject needs to be made aware of `ssize_t` as a new supported type.

**Comment by bluca** [comment]
Returning off_t is actually the right thing as it's forward compatible with Large File Support:

https://lintian.debian.org/tags/binary-file-built-without-LFS-support.html

IMHO it's better to just keep that one off the API rather than adding deprecated stuff to zproject

**Pull request merged**
