### PR TITLE
Fixed typographical error, changed accomodate to accommodate in README.

### PR DESCRIPTION
**Pull request by orthographic-pedant**
zeromq, I've corrected a typographical error in the documentation of the [czmq](https://github.com/zeromq/czmq) project. You should be able to merge this pull request automatically. However, if this was intentional or you enjoy living in linguistic squalor please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.

### CODE REVIEW

**Comment by jemc** [comment]
This PR seems to be created by a bot rather than a human, and doesn't follow the contributing guidelines for the project.

However, the main problem is that this doesn't fix the root issue, in which the docstring for the function has a mispelling.  If we fix it in the README and not in the source, this change will only get squashed later, which is commit noise.

If this were a human, I would merge it anyway to encourage contributions, but since it seems to be a bot, I have no problem squashing its hopes and dreams.

**Comment by hintjens** [comment]
Spoiler: the bot, feeling quashed and rejected, grows up to become Skynet
and the Destroyer of Humanity.

**Comment by thoppe** [comment]
There is still a wizard behind the screen, directing the shadowy actions of the bot. 

In regards to your point @jemc, feel free to close this PR and open a new one that corrects the docstrings in the code as well. Think of this is a public service announcement. If you are happy leaving the typographical error in both places I won't argue (but I'm sure @orthographic-pedant will silently judge you).

**Comment by jemc** [comment]
@thoppe Right, I'll probably do the proper fix PR when I have time away from other projects to do it.

Meanwhile, as our pedant requested, I opened [an issue ticket](https://github.com/thoppe/orthographic-pedant/issues/10) that suggests an approach for making the service more useful in these situations.

**Pull request closed without merging**
