### PR TITLE
Problem: Python tests failing.

### PR DESCRIPTION
**Pull request by twhittock**
Solution: Regenerate using latest zproject to correctly decorate methods which match a keyword

### CODE REVIEW

**Comment by bluca** [comment]
@twhittock - thanks for fixing the Python tests.
Was there a specific reason for removing the autoconf and CMake project-local hooks? They were merged in Zproject a few days ago. If not, then I opened PR #1052 to re-generate from the latest Zproject version.

**Comment by jemc** [comment]
@bluca - I'm sure it was just an accident from not having the latest zproject master when @twhittock regenerated.

**Comment by twhittock** [comment]
yes purely accidental, sorry about that.

**Comment by bluca** [comment]
Ah I see, no problem at all!  :-)
Thanks again for fixing the Python CI build, now the CI build is all nice and green: https://travis-ci.org/zeromq/czmq/builds/73401535

**Pull request merged**
