### PR TITLE
Add client server to czmq

### PR DESCRIPTION
**Pull request by somdoron**
* Add the socket type to zsock
* Retrieving and setting the routing id on zframe

### CODE REVIEW

**Comment by taotetek** [comment]
Hi @somdoron !  Tests are currently failing for this PR and I don't currently have a moment to look at why - but this is a very exciting PR!  Can look this afternoon if no one else has jumped in.

**Comment by somdoron** [comment]
Thanks. I will check it now...

**Comment by somdoron** [comment]
so it is failing for builds that don't have server & client (zeromq 4.1,4, 3,2).

Is there a macro for zeromq version that I can use?

**Comment by taotetek** [comment]
@somdoron I -think- ZMQ_VERSION_MAJOR and ZMQ_VERSION_MINOR but I could be remembering incorrectly.

**Comment by taotetek** [comment]
@somdoron - aha - and zsys_version in zsys for runtime version detection

**Comment by somdoron** [comment]
So I'm checking the ZEROMQ version now:

https://github.com/somdoron/czmq/commit/9342fa2cce899d187ad62bcc75e546e97b27f92c

However I'm not big fun of it, so I you have a more elegant solution let me know...

**Comment by taotetek** [comment]
@somdoron if the tests pass I say let's merge it, and if someone has a more elegant solution for managing the tests that can come in a follow up PR.

I'm going to add support to goczmq for this today so I can start playing with the new types.  Fun!  I remember the conversations around this idea :)

**Comment by somdoron** [comment]
Cool, I'm going to add support to zproto as well.

**Comment by Asmod4n** [comment]
You can check for server and client sockets via
```c
#if defined(ZMQ_SERVER) && defined(ZMQ_CLIENT)
#endif
```

**Pull request merged**
