### PR TITLE
Problem: zmsg_load marked as singleton in api model

### PR DESCRIPTION
**Pull request by vyskocilm**
Solution: remove singleton flag and first parameter (implicit for non
singleton methods).

### CODE REVIEW

**Comment by jemc** [comment]
@vyskocilm - This doesn't seem correct.

The method descriptions says:
> Load/append an open file into message, create new message if null message provided. Returns NULL if the message could not be loaded.

Your change makes it impossible to use the "create new message if null message provided" behavior.

I suggest reverting this.

**Comment by hintjens** [comment]
Do we always assert that self is not null then?

**Comment by jemc** [comment]
@hintjens - Not sure I understand your question.

No, we're not asserting self in `zmsg_load` - it behaves as described and creates a new zmsg in that case - https://github.com/zeromq/czmq/blob/d2b7b08469da4cb11b1afbd824df4cffdd4ee9d9/src/zmsg.c#L616-L617

**Comment by vyskocilm** [comment]
OK, I see - API is quite confusing. Then yes, please revert it ...

**Comment by hintjens** [comment]
So I don't understand why making it a non-singleton stops one passing null
as self...

**Comment by paddor** [comment]
This function does too much IMO. Either way the return value is either fresh or non-fresh, which makes the API wrong in some cases.

**Comment by jemc** [comment]
> So I don't understand why making it a non-singleton stops one passing null as self...

Most object-oriented languages don't allow the `self` argument to be explicitly passed at all.  It's just always the receiver of the method.  So in this case, you'd have to call the equivalent of the pseudocode `NULL.load(file)`, which doesn't work because `NULL` doesn't have a `load` method because it isn't an instance of the `zmsg` class.

So, in almost all object-oriented language, `self`/`this` must always be an instance of the class, and you can't call it any other way.  It may work in the Python bindings, but Python is a bit of an anomaly in this way (letting you pass in an arbitrary `self` value).

A singleton method is not associated with any specific instance, so the "self" argument is an explicit value passed in like any other argument - it is not special like it is for an instance method.

> This function does too much IMO. Either way the return value is either fresh or non-fresh, which makes the API wrong in some cases.

This is an excellent point.

In light of this point, rather than reverting this patch I think we should deprecate calling `zmsg_load` with a `NULL` self (though we probably shouldn't break compatibility by removing it), and create a separate method that *always* creates a new (fresh) `zmsg`.

**Comment by hintjens** [comment]
Yes, I agree. I'd be fine with breaking the API here, and removing the self argument entirely. It is fuzzy and inconsistent with all other methods (self cannot be null, by convention).

**Comment by hintjens** [comment]
In the name of science, I propose we deliberately break the API on this method and see if anyone complains. :-) 

I searched github and found this method used mainly in the titanic pattern (from the Guide).

**Comment by jemc** [comment]
Okay by me.  I'd suggest an API like this:

```
    <constructor name = "load new">
        Load/append an open file into a new message.
        Returns NULL if the message could not be loaded.
        <argument name = "file" type = "FILE" />
    </constructor>

    <method name = "load">
        Load/append an open file into the message.
        Returns NULL if the message could not be loaded.
        <argument name = "file" type = "FILE" />
        <return type = "zmsg" />
    </method>
```

If we agree, I can take care of it in a day or so if no one else beats me to it.

**Comment by hintjens** [comment]
I'd be more brutal: no-one needs the "load into existing message" functionality, it's bogus and breaks the API conventions:

    <constructor name = "load">
        Load/append an open file into a new message.
        Returns NULL if the message could not be loaded.
        <argument name = "file" type = "FILE" />
    </constructor>

**Comment by twhittock** [comment]
Please also see #949

**Comment by hintjens** [comment]
Anyone know of a reason other constructors (e.g. zframe_new_empty) are defined as singletons instead of constructors?

**Comment by jemc** [comment]
@hintjens - No reason I can see.  You're right, they (`zframe`'s `new empty`, `from`, and `recv` methods) should be defined as `constructor`s by convention. A `constructor` implies a `singleton` that returns a `fresh` instance, but we should call them `constructor`s wherever it fits this pattern, just for clarity..

**Comment by hintjens** [comment]
OK, cleaning this up now.

**Comment by paddor** [comment]
I think I had this idea before but then stopped for some reason... I think it was something about one of the bindings... Oh right! I think the python bindings can't handle it. Only one `__init__` possible.

**Comment by paddor** [comment]
I think I even had the python binding fixed (I made only the constructor named `new` become __init__). But there was another thing as well... so I didn't proceed.

**Comment by hintjens** [comment]
@paddor we can handle this by only treating the first constructor as __init__ and the rest as methods... we should not expose this to the API model IMO.

**Comment by jemc** [comment]
Agreed, we should patch the python bindings to be able to deal with more than one constructor.

**Comment by paddor** [comment]
@hintjens True. I hope you'll hit no other problem.

**Comment by hintjens** [comment]
Well, let's force this through. :-)

**Comment by paddor** [comment]
I remember the problem now. How do you do it in Java? A constructor in Java always has the same name as the class, right? Or would you just implement it as a class method? Can't depend on the fact that all constructors have a different signature...

**Comment by jemc** [comment]
@paddor - Yes, we would do it as a singleton method in Java and Python, just as we do in Ruby (where you can only have one constructor called `new`).

However, it makes sense to keep those implementation details out of the API model, as these are all conceptually constructors, and some language bindings will actually support multiple constructors.

**Comment by hintjens** [comment]
I guess for Java I'll only use the 'new' constructor and treat the others as methods.

**Comment by paddor** [comment]
Sure, I love the idea. Just wanted to warn about the problems. It's probably no problem for someone who actually knows Java/Python. I don't. :sweat_smile:

**Comment by hintjens** [comment]
I'll deal with the JNI binding now. Am first fixing all the class files, there's a bunch of these...

**Comment by twhittock** [comment]
I did a lot of these singleton-as-constructor things - I wasn't aware zproject could do more than one constructor. No other reason. Hence the Python bindings' lack of support for the construct, also.

**Comment by hintjens** [comment]
@twhittock makes sense, thanks. As a general rule, when/if we see semantics in the API model that can be improved, we should take the pain now. E.g. methods that pass data back via mutable arguments, or by reference (ghastly IMO).

**Comment by hintjens** [comment]
OK, fixed in zproject_class_api.gsl: https://github.com/zeromq/zproject/pull/368

**Pull request merged**
