### PR TITLE
ZFrame metadata getter

### PR DESCRIPTION
**Pull request by petehayes102**
This is a tiny PR, but I can't see another way to get access to frame metadata.

### CODE REVIEW

**Comment by sappo** [comment]
@petehayes102  could you please in short state what's your problem and how this PR solves it. Thanks!

**Comment by petehayes102** [comment]
Sure. I have an app that uses ZAuth to authenticate clients. I want to be able to access message meta data without having to directly use a ZMQ message (i.e. use CZMQ structs instead). ZFrame uses zmq_msg_t under the hood, so this is a good place to retrieve metadata, e.g. user ID, via zmq_msg_gets().

My PR provides a CZMQ wrapper to get message meta data from a ZFrame, which currently doesn't seem possible in CZMQ.

**Comment by sappo** [comment]
Okay, thanks!

For further contributions it would be great if you describe the Problem you're having and the Solution in your commit message really short. Have a look at the commit log for some examples if you need any. This usually speeds up merging of a PR.

**Comment by petehayes102** [comment]
Sure. Sorry about that!

**Comment by bluca** [comment]
Is this intended to be a public API?

If so, it should be added to the headers via api/zframe.api and regeneration through zproject. And also it should be unit-tested.

**Comment by petehayes102** [comment]
Ok, I didn't know about the api thing. I'll raise another PR with the missing bits.

**Comment by bluca** [comment]
Thanks!

**Pull request merged**
