### PR TITLE
OSX CI build fails due to upstream curl change

### PR DESCRIPTION
**Pull request by sphaero**
Problem: Curl needs a configure option for encryption
Solution: add config option to zproject config

### CODE REVIEW

**Comment by sphaero** [comment]
as mentioned in #2188 I'm not sure this is the best cross platform solution. Suggestions welcome

**Comment by bluca** [comment]
if it's a new option, shouldn't we detect the version and use it conditionally? Otherwise backward compat will break, no?

**Comment by sphaero** [comment]
I think this is only used in the ci_build.sh script which does a git clone of the master repo: https://github.com/zeromq/czmq/blob/b30fc4288e9241dc4d7cd562327c9db0a6c53c4f/ci_build.sh#L346

So there's no versioning involved currently. Zproject does have some versioning params but I don't think they are used either.

**Comment by bluca** [comment]
Ah yes of course, good point

**Pull request merged**
