### PR TITLE
Problem: valgrind build fails

### PR DESCRIPTION
**Pull request by vyskocilm**
Solution: destroy the poller and add a suppression for glibc thread pool. Plus document the test and code better.

### CODE REVIEW

**Comment by vyskocilm** [comment]
Local memcheck pass, but not on Travis. I'll check it why.

@bluca @sappo - any idea about docs test, it looks strange to me.

**Comment by vyskocilm** [comment]
OK, memcheck looks like the problem with execve and the fact binary was not found or executed properly. I skipp the test in this case, need to make this resource allocation easier to use from tests.

**Comment by sappo** [comment]
@vyskocilm I started the work on docs but haven't gotten around to finish it. Thanks for deactivating them.

**Comment by vyskocilm** [comment]
So, can be merged.
 * The getline is over, zsp use zfile instead. Fixes android
 * Valgrind test is skipped on Travis as I can't find zsp binary there.
 * docs target is disabled
 * appveyor fails on zdir only

**Comment by bluca** [comment]
Thanks!

**Pull request merged**
