### PR TITLE
Problem: czmq gatekeepers did not like zsubproc name

### PR DESCRIPTION
**Pull request by vyskocilm**
Solution: merge the code with zproc

Note that zproc_run is missing from include file as there is no way how to express it via API model. This needs to be solved later.

fixes: https://github.com/zeromq/czmq/pull/1636

### CODE REVIEW

**Comment by bluca** [comment]
Great, thanks!

**Comment by sappo** [comment]
czmq gatekeepers :rofl:

**Comment by bluca** [comment]
Here's a picture of Zuul, the Gatekeeper of CZMQ:

http://vignette2.wikia.nocookie.net/ghostbusters/images/3/37/ZuulTerrorDog1.png/revision/latest/scale-to-width-down/350?cb=20140515200520

**Comment by vyskocilm** [comment]
Was he at hackaton? :-D

Dne 19. 3. 2017 19:54 napsal uživatel "Luca Boccassi" <
notifications@github.com>:

**Pull request merged**
