### PR TITLE
Run Travis CI on all supported archs

### PR DESCRIPTION
**Pull request by TBK**

### CODE REVIEW

**Comment by bluca** [comment]
Given the tests are failing, can s390 be marked as "ignored"?

**Comment by TBK** [comment]
It should be possible with `allow_failures` - https://docs.travis-ci.com/user/conditional-builds-stages-jobs#conditionally-allowing-jobs-to-fail

I will experiment a bit and then update the PR.

**Comment by bluca** [comment]
@TBK any update?

**Comment by TBK** [comment]
@bluca I had some time yesterday to look at it and have made the changes to allow_failures for s390x.

**Comment by bluca** [comment]
thanks, but it looks like the other new archs are failing too?

**Comment by TBK** [comment]
I have now added the others as well.

**Comment by sphaero** [comment]
Any thought on this? Two OSX test fail  on zdir:
```
Assertion failed: (polled == watch), function zdir_test, file src/zdir.c, line 1106.
```
And Windows fails due to a Java error:
```
ERROR: JAVA_HOME is set to an invalid directory: C:\Program Files\OpenJDK\jdk-13.0.2

Please set the JAVA_HOME variable in your environment to match the

location of your Java installation.
```
Both are not related. So can we merge this?

**Comment by sphaero** [comment]
Btw, the travis config file is generated by zproject. So this better gets into zproject? Otherwise it will be overwritten.

**Pull request closed without merging**
