### PR TITLE
Issue #1152 - First working version of CZMQ JNI binding

### PR DESCRIPTION
**Pull request by trevorbernard**

### CODE REVIEW

**Comment by jemc** [comment]
I have my doubts about including bindings that are not code-generated into the main CZMQ repository - I worry mainly that they cannot be kept up to date in the future and we'll have dead code lying around.  Also, having some bindings be generated and others not generated is likely to cause confusion among contributors.

If these bindings can't be generated via zproject, why not create a separate repository for these, as is already common for handwritten zeromq-related bindings to other languages?

**Comment by jemc** [comment]
By project guidelines, I will merge anyway, but I have serious doubts about this PR.

**Comment by trevorbernard** [comment]
It was per @hintjens request. The goal is to create a working version then slowly replace with code generation

**Comment by jemc** [comment]
:+1:

**Comment by hintjens** [comment]
Yes, this is designed obsolescence...  :)

**Pull request merged**
