### PR TITLE
Problem: zpoller test are failing

### PR DESCRIPTION
**Pull request by somdoron**
Had a bug in the test

### CODE REVIEW

**Comment by somdoron** [comment]
can be merged now.

**Comment by sappo** [comment]
@somdoron zpoller is failing on my machine with:
```
lt-czmq_selftest: src/zpoller.c:515: zpoller_test: Assertion `which == server' failed.
 * zpoller: make[2]: *** [check-local] Aborted (core dumped)
```
I tried to figure out why and the only thing I could observe was that the zpoller_wait function in line 514 for whatever reason was never entered.

**Comment by sappo** [comment]
Nevermind, forgot to update libzmq to latest version

**Comment by somdoron** [comment]
Ok, anyway I will change the macro of the test to check that the zmq_poller exist (it is now checking if thread safe supported)

**Pull request merged**
