### PR TITLE
Problem: zsock_option.xml is not installed

### PR DESCRIPTION
**Pull request by sappo**
Solution: use latest zproject to install this file as well

### CODE REVIEW

**Comment by hintjens** [comment]
Did you modify src/Makemodule.am by hand, or regenerate it from project.xml? This commit seems incomplete...

**Comment by sappo** [comment]
I regenerated it from project.xml.

**Comment by hintjens** [comment]
I realized after I commented. :)

**Comment by sappo** [comment]
I think I pushed the commit to zproject while you where already on the merge page. In thus it sneaked by you.

**Pull request merged**
