### PR TITLE
Problem: interrupt handling was retired, but replacement is draft

### PR DESCRIPTION
**Pull request by bluca**
Solution: declare zloop/zpoller_set_nonstop as stable in order to
provide an alternative. The implementation is identical to the
previous one, just the names were changed.

Then regenerate code and docs.

### CODE REVIEW

**Comment by bluca** [comment]
@sappo thanks! Gonna push 4.0 now

**Comment by bluca** [comment]
@sappo - I think there's a problem with the bindings deploy, perhaps because of duplicated names due to the 4.0.0-rc1?

```
* What went wrong:
Execution failed for task ':bintrayUpload'.
> Could not upload to 'https://api.bintray.com/content/zeromq/maven/czmq-jni/4.0.0/org/zeromq/czmq-jni/4.0.0/czmq-jni-4.0.0.jar': HTTP/1.1 409 Conflict [message:Unable to upload files: An artifact with the path 'org/zeromq/czmq-jni/4.0.0/czmq-jni-4.0.0.jar' already exists]
```

https://travis-ci.org/zeromq/czmq/jobs/173286746

**Comment by sappo** [comment]
Hi Luca,

okay, that's no blocker. I'll have a look at it next week and fix it
manually.

//Kevin

Am 05.11.2016 01:13 schrieb "Luca Boccassi" <notifications@github.com>:

**Comment by bluca** [comment]
Thanks!

**Pull request merged**
